(()=>{"use strict";
const KEY="jacky_ai_final_v3",D={salary:[],farm:[],expense:[],home:[],loans:[],temp:[],perm:[],reminders:[]};let DB=load(),rec=null;
const $=x=>document.getElementById(x),uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2),now=()=>new Date().toISOString(),money=x=>Number(x||0).toLocaleString("en-IN"),dt=x=>new Date(x).toLocaleString("ta-IN",{dateStyle:"short",timeStyle:"short"});
function load(){try{return {...D,...JSON.parse(localStorage.getItem(KEY)||"{}")}}catch(e){return {...D}}}function save(){localStorage.setItem(KEY,JSON.stringify(DB));render()}
function show(n){document.querySelectorAll(".page").forEach(x=>x.classList.remove("active"));$(n)?.classList.add("active")}window.showPage=show;
function add(b,x){DB[b].push({id:uid(),date:now(),...x});save()}function del(b,id){DB[b]=DB[b].filter(x=>x.id!==id);save()}window.deleteById=del;
function rh(b,x,a,s){return`<div class="record"><div><b>${a}</b><small>${s}</small></div><button class="danger" onclick="deleteById('${b}','${x.id}')">🗑️</button></div>`}
function person(t){if(/மணிமேகலை|\bmm\b/i.test(t))return"மணிமேகலை (MM)";if(/கலைசெந்தாமரை|\bks\b/i.test(t))return"கலைசெந்தாமரை (KS)";return""}
function amt(t){let m=t.match(/[\d,]+(?:\.\d+)?/),n=m?+m[0].replace(/,/g,""):0;if(/லட்சம்/.test(t))n=(n||1)*1e5;else if(/ஆயிரம்/.test(t))n=(n||1)*1e3;return n}
function src(t){if(/வீட்டு பணம்|வீட்டு கணக்கு|வீட்டிலிருந்து|வீட்டு பணத்தில்/.test(t))return"home";if(/சம்பள பணம்|சம்பள கணக்கு|சம்பளத்தில்|சம்பளத்திலிருந்து/.test(t))return"salary";if(/கொல்லை பணம்|கொல்லை கணக்கு|கொல்லையில்/.test(t))return"farm";return null}
function cat(t){if(/பெட்ரோல்|petrol|டீசல்|diesel/.test(t))return"பெட்ரோல்";if(/மருந்து/.test(t))return"மருந்து";if(/உரம்/.test(t))return"உரம்";if(/சாப்பாடு|உணவு/.test(t))return"சாப்பாடு";if(/காய்கறி/.test(t))return"காய்கறி";if(/உடை|துணி|dress/.test(t))return"உடை";return"மற்ற செலவு"}
function addExpense(n,a,s,p){let e={id:uid(),date:now(),note:n,amt:a,source:s,person:p};DB.expense.push(e);if(s==="home")DB.home.push({id:uid(),date:e.date,type:"out",amt:a,note:n+(p?" — "+p:""),linked:e.id});if(s==="salary")DB.salary.push({id:uid(),date:e.date,type:"out",amt:a,note:n+(p?" — "+p:""),linked:e.id});if(s==="farm")DB.farm.push({id:uid(),date:e.date,amt:a,note:n,linked:e.id});save()}
window.addSalary=t=>{let a=+$("salaryAmount").value;if(a>0)add("salary",{type:t,amt:a,note:$("salaryNote").value.trim()||"நேரடி"});$("salaryAmount").value=$("salaryNote").value=""};
window.addHome=t=>{let a=+$("homeAmount").value;if(a>0)add("home",{type:t,amt:a,note:$("homeNote").value.trim()||"நேரடி"});$("homeAmount").value=$("homeNote").value=""};
window.addExpenseManual=()=>{let n=$("expenseNote").value.trim(),a=+$("expenseAmount").value,p=person($("expensePerson").value),s=$("expenseSource").value;if(n&&a>0)addExpense(n,a,s,p);$("expenseNote").value=$("expenseAmount").value=$("expensePerson").value=""};
window.addFarm=()=>{let a=+$("farmAmount").value,n=$("farmNote").value.trim()||"கொல்லை செலவு",s=$("farmSource").value;if(a>0)addExpense(n,a,s,"");$("farmAmount").value=$("farmNote").value=""};
window.addLoan=()=>{let n=$("loanName").value.trim(),a=+$("loanAmount").value,r=+$("loanRate").value,d=$("loanDate").value||new Date().toISOString().slice(0,10);if(n&&a>0)add("loans",{name:n,amt:a,rate:r,startDate:d,interestPaid:[]});$("loanName").value=$("loanAmount").value=$("loanRate").value=""};
window.addNote=t=>{let e=t==="temp"?$("tempText"):$("permText"),v=e.value.trim();if(v)add(t==="temp"?"temp":"perm",{text:v});e.value=""};window.clearTemporary=()=>{if(confirm("அனைத்து தற்காலிக குறிப்புகளையும் அழிக்கவா?")){DB.temp=[];save()}};
window.addReminder=()=>{let text=$("reminderText").value.trim(),d=$("reminderDate").value,time=$("reminderTime").value,early=+$("reminderEarly").value||60;if(!text||!d||!time)return;add("reminders",{text,target:new Date(d+"T"+time).toISOString(),early,earlyDone:false,done:false});$("reminderText").value=""};
window.requestNotifications=async()=>{if(!("Notification"in window))return alert("Notification ஆதரவு இல்லை");let p=await Notification.requestPermission();alert(p==="granted"?"அனுமதி கிடைத்தது":"அனுமதி இல்லை")};
function speak(t){if("speechSynthesis"in window){speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(t);u.lang="ta-IN";u.rate=.95;speechSynthesis.speak(u)}}function msg(t,k){let e=document.createElement("div");e.className="message "+k;e.textContent=t;$("chatBox").appendChild(e);$("chatBox").scrollTop=$("chatBox").scrollHeight}window.clearChat=()=>{$("chatBox").innerHTML='<div class="message ai">Chat அழிக்கப்பட்டது.</div>'};
function reminder(t){if(!/(ஞாபகப்படுத்து|நினைவூட்டு|நினைவில் வை|remind)/i.test(t))return null;let d=new Date;if(/நாளை|நாளைக்கு/.test(t))d.setDate(d.getDate()+1);let m=t.match(/(\d{1,2})(?:[:.](\d{1,2}))?\s*(மணி|am|pm)?/i);if(m){let h=+m[1],mi=+(m[2]||0),ap=(m[3]||"").toLowerCase();if(ap==="pm"&&h<12)h+=12;if(ap==="am"&&h===12)h=0;d.setHours(h,mi,0,0)}let em=t.match(/(\d+)\s*நிமிடம்/),early=em?+em[1]:60,clean=t.replace(/ஞாபகப்படுத்து|நினைவூட்டு|நினைவில் வை|remind/gi,"").replace(/நாளை|நாளைக்கு/gi,"").replace(/(\d{1,2})(?:[:.](\d{1,2}))?\s*(மணி|am|pm)?/i,"").replace(/(\d+)\s*நிமிடம்/,"").trim()||"நினைவூட்டல்";add("reminders",{text:clean,target:d.toISOString(),early,earlyDone:false,done:false});return`சரி. “${clean}” — ${dt(d)}. ${early} நிமிடம் முன்பும் நினைவூட்டுவேன்.`}
function interest(t){if(!/வட்டி|அசல்|தரணும்|கடன்/.test(t))return null;let l=DB.loans.find(x=>t.toLowerCase().includes(x.name.toLowerCase()));if(!l){if(/எல்லா|யார்|பட்டியல்/.test(t))return"வட்டி பட்டியல்:\n"+DB.loans.map(x=>`${x.name} — ₹${money(x.amt)} — ${x.rate}%`).join("\n");return"யாருடைய வட்டி கணக்கு வேண்டும்? பெயரைச் சொல்லுங்கள்."}let st=new Date(l.startDate),n=new Date,m=Math.max(0,(n.getFullYear()-st.getFullYear())*12+n.getMonth()-st.getMonth()+1),mi=l.amt*l.rate/100,ti=mi*m,paid=(l.interestPaid||[]).reduce((a,x)=>a+x.amt,0),due=Math.max(0,ti-paid);return`${l.name} முழு கணக்கு:\nஅசல் ₹${money(l.amt)}\nமாத வட்டி ${l.rate}% = ₹${money(mi)}\nமாதங்கள் ${m}\nமொத்த வட்டி ₹${money(ti)}\nசெலுத்திய வட்டி ₹${money(paid)}\nமீதமுள்ள வட்டி ₹${money(due)}\nமொத்தம் தர வேண்டியது ₹${money(l.amt+due)}\nதொடக்கம் ${l.startDate}`}
function expQuery(t){if(!/(எவ்வளவு|என்னென்ன|மொத்தம்)/.test(t))return null;let c=cat(t),p=person(t),s=src(t),d=new Date,n=/இந்த மாதம்|இந்த மாசம்/.test(t),from=n?new Date(d.getFullYear(),d.getMonth(),1):null,to=n?new Date(d.getFullYear(),d.getMonth()+1,1):null,r=DB.expense.filter(x=>(c==="மற்ற செலவு"||x.note===c)&&(!p||x.person===p)&&(!s||x.source===s)&&(!from||new Date(x.date)>=from)&&(!to||new Date(x.date)<to));if(!r.length)return"அந்த நிபந்தனைக்கு செலவு பதிவு இல்லை.";let total=r.reduce((a,x)=>a+x.amt,0);return`${p?p+" — ":""}${c} செலவு மொத்தம் ₹${money(total)}\n`+r.map(x=>`• ${x.note} ₹${money(x.amt)} • ${x.person||"பொது"} • ${x.source==="home"?"வீடு":x.source==="salary"?"சம்பளம்":"கொல்லை"}`).join("\n")}
function allExp(t){if(!/என்னென்ன செலவு|மொத்த செலவு|இந்த மாத செலவு|இந்த மாசம் செலவு/.test(t))return null;let d=new Date,f=new Date(d.getFullYear(),d.getMonth(),1),to=new Date(d.getFullYear(),d.getMonth()+1,1),r=DB.expense.filter(x=>new Date(x.date)>=f&&new Date(x.date)<to),g={};r.forEach(x=>g[x.note]=(g[x.note]||0)+x.amt);let total=r.reduce((a,x)=>a+x.amt,0);return`இந்த மாத மொத்த செலவு ₹${money(total)}\n`+Object.entries(g).map(([k,v])=>`• ${k}: ₹${money(v)}`).join("\n")}
function balance(t){if(/சம்பள.*மீதி|salary.*balance/i.test(t))return`சம்பள மீதி ₹${money(DB.salary.reduce((a,x)=>a+(x.type==="in"?x.amt:-x.amt),0))}`;if(/வீட்டு.*மீதி|home.*balance/i.test(t))return`வீட்டு மீதி ₹${money(DB.home.reduce((a,x)=>a+(x.type==="in"?x.amt:-x.amt),0))}`;return null}
window.sendMessage=()=>{let i=$("textInput"),t=i.value.trim();if(!t)return;msg(t,"user");i.value="";let r=reminder(t)||interest(t)||allExp(t)||expQuery(t)||balance(t);if(!r&&/(பெட்ரோல்|மருந்து|உரம்|சாப்பாடு|காய்கறி|உடை|செலவு|வாங்கினேன்)/.test(t)){let a=amt(t),s=src(t),p=person(t),c=cat(t);if(a&&s){addExpense(c,a,s,p);r=`சரி. ${p?p+"க்கு ":""}${c} ₹${money(a)} பதிவு செய்தேன். ${s==="home"?"வீட்டு":s==="salary"?"சம்பள":"கொல்லை"} பணத்திலிருந்து குறைத்தேன்.`}else if(a)r="செலவு எந்த பணத்தில் இருந்து? வீட்டு பணமா, சம்பள பணமா, கொல்லை பணமா?"}if(!r)r="இந்த கேள்விக்கான செயலை இன்னும் அமைக்கவில்லை. கணக்கு, செலவு, வட்டி அல்லது நினைவூட்டல் என்று தெளிவாகச் சொல்லுங்கள்.";msg(r,"ai");speak(r)};
function setup(){let SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){$("status").textContent="Voice ஆதரவு இல்லை";return}rec=new SR;rec.lang="ta-IN";rec.continuous=false;rec.interimResults=false;rec.onstart=()=>$("status").textContent="🎙️ கேட்கிறேன்...";rec.onresult=e=>{$("textInput").value=e.results[0][0].transcript.trim();sendMessage()};rec.onend=()=>$("status").textContent="🎤 தயார்";rec.onerror=e=>$("status").textContent="Voice error: "+e.error}window.startListening=()=>{try{rec?.start()}catch(e){}};window.stopListening=()=>rec?.stop();
function reminders(){let n=Date.now(),ch=false;DB.reminders.forEach(r=>{if(r.done)return;let t=new Date(r.target).getTime(),e=t-(r.early||0)*60000;if(!r.earlyDone&&r.early>0&&n>=e&&n<t){let m=`⏰ ${r.text} — இன்னும் ${r.early} நிமிடம்.`;msg(m,"ai");speak(m);if("Notification"in window&&Notification.permission==="granted")new Notification("Jacky AI",{body:m});r.earlyDone=true;ch=true}if(n>=t){let m=`🔔 இப்போது: ${r.text}`;msg(m,"ai");speak(m);if("Notification"in window&&Notification.permission==="granted")new Notification("Jacky AI",{body:m});r.done=true;ch=true}});if(ch)save()}
function render(){let sb=DB.salary.reduce((a,x)=>a+(x.type==="in"?x.amt:-x.amt),0),hb=DB.home.reduce((a,x)=>a+(x.type==="in"?x.amt:-x.amt),0),d=new Date,f=new Date(d.getFullYear(),d.getMonth(),1),to=new Date(d.getFullYear(),d.getMonth()+1,1),me=DB.expense.filter(x=>new Date(x.date)>=f&&new Date(x.date)<to).reduce((a,x)=>a+x.amt,0);$("salaryBalance").textContent=money(sb);$("homeBalance").textContent=money(hb);$("summarySalary").textContent="₹"+money(sb);$("summaryHome").textContent="₹"+money(hb);$("summaryExpense").textContent="₹"+money(me);$("summaryRem").textContent=DB.reminders.filter(x=>!x.done).length;$("salaryList").innerHTML=DB.salary.slice().reverse().map(x=>rh("salary",x,(x.type==="in"?"+ ":"− ")+"₹"+money(x.amt),x.note+" • "+dt(x.date))).join("")||"பதிவு இல்லை";$("homeList").innerHTML=DB.home.slice().reverse().map(x=>rh("home",x,(x.type==="in"?"+ ":"− ")+"₹"+money(x.amt),x.note+" • "+dt(x.date))).join("")||"பதிவு இல்லை";$("expenseList").innerHTML=DB.expense.slice().reverse().map(x=>rh("expense",x,"₹"+money(x.amt)+" • "+x.note,(x.person||"பொது")+" • "+(x.source==="home"?"வீடு":x.source==="salary"?"சம்பளம்":"கொல்லை")+" • "+dt(x.date))).join("")||"பதிவு இல்லை";$("farmList").innerHTML=DB.farm.slice().reverse().map(x=>rh("farm",x,"₹"+money(x.amt),x.note+" • "+dt(x.date))).join("")||"பதிவு இல்லை";$("loanList").innerHTML=DB.loans.slice().reverse().map(x=>rh("loans",x,x.name+" • ₹"+money(x.amt),x.rate+"% / மாதம் • "+x.startDate)).join("")||"வட்டி பதிவு இல்லை";$("tempList").innerHTML=DB.temp.slice().reverse().map(x=>rh("temp",x,x.text,dt(x.date))).join("")||"குறிப்பு இல்லை";$("permList").innerHTML=DB.perm.slice().reverse().map(x=>rh("perm",x,x.text,dt(x.date))).join("")||"குறிப்பு இல்லை";$("reminderList").innerHTML=DB.reminders.slice().reverse().map(x=>rh("reminders",x,"⏰ "+x.text,dt(x.target)+" • "+x.early+" நிமிடம் முன்")).join("")||"நினைவூட்டல் இல்லை"}
document.addEventListener("DOMContentLoaded",()=>{setup();render();let d=new Date;d.setDate(d.getDate()+1);$("reminderDate").value=d.toISOString().slice(0,10);if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js?v=3").catch(()=>{});setInterval(reminders,30000);reminders()});
})();